# Generated by Django 5.0.6 on 2024-05-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
