# Generated by Django 5.0.6 on 2024-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
