# Generated by Django 5.0.6 on 2024-05-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order_count',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.cart'),
        ),
    ]
