# Generated by Django 5.0.6 on 2024-05-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_discount', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
            ],
        ),
    ]
